# Generated by Django 5.2.4 on 2025-08-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_number', models.PositiveIntegerField(unique=True, verbose_name='Número de Partido')),
                ('party_name', models.CharField(max_length=50, verbose_name='Nombre del Partido')),
                ('president', models.CharField(max_length=100, verbose_name='Presidente')),
                ('vice_president', models.CharField(max_length=100, verbose_name='Vicepresidente')),
                ('slogan', models.CharField(max_length=100, verbose_name='Eslogan')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='VotingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.BooleanField(default=False, verbose_name='Cerrado?')),
                ('date_time_close', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Localidad')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Zona')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.locality', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.PositiveIntegerField(unique=True, verbose_name='DNI')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('voted', models.BooleanField(default=False, verbose_name='Votó?')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('afirmativo', 'Afirmativo'), ('blanco', 'En blanco'), ('nulo', 'Nulo'), ('recurrido', 'Recurrido'), ('impugnado', 'Identidad impugnada')], default='afirmativo', max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('political_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.politicalparty')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
    ]
